export const cls = {
  blocks: 'blocks',
  block: 'block',
  boqBlock: 'boq-block',
  priceBlock: 'price-block',
  textBlock: 'text-block',
  paper: 'paper',
  actionsContainer: 'actions-container',
  boqRows: 'boq-rows',
  boqRow: 'boq-row',
  pin: 'pin',
  searchAutocomplete: 'search-autocomplete',
  search: 'search',
  actionIconContainer: 'action-icon-container',
  actionIcon: 'action-icon',
} as const
