export const cls = {
  blocks: 'blocks',
  block: 'block',
  priceBlock: 'price-block',
  textBlock: 'text-block',
  paper: 'paper',
  blockActions: 'item-actions',
  boqRowActions: 'item-actions',
  actionsContainer: 'actions-container',
  boqRows: 'boq-rows',
  boqRow: 'boq-row',
  pin: 'pin',
  searchAutocomplete: 'search-autocomplete',
  search: 'search',
} as const
