export const navItemKey = {
  top: 'top',
  pending: 'pending',
  new: 'new',
  save: 'save',
  share: 'share',
  pdf: 'pdf',
  link: 'link',
  excel: 'excel',
  insert: 'insert',
  quotations: 'quotations',
  bookmarks: 'bookmarks',
  login: 'login',
  profile: 'profile',
  settings: 'settings',
  logout: 'logout',
  block: 'block',
  textItem: 'textItem',
  boqItem: 'boqItem',
  priceItem: 'priceItem',
  boqRow: 'boqRow',
  back: 'back',
  admin: 'admin',
  users: 'users',
  visitors: 'visitors',
} as const

export type NavItemKey = (typeof navItemKey)[keyof typeof navItemKey]
