export const route = {
  root: '/',
  login: 'login',
  logout: 'logout',
  register: 'register',
  requestPasswordReset: 'request-password-reset',
  resetPassword: 'reset-password',
  activate: 'activate',
  new: 'new',
  quotations: 'quotations',
  save: 'save',
  bookmarks: 'bookmarks',
  bookmark: 'bookmark',
  info: 'info',
  settings: 'settings',
  admin: 'admin',
} as const
