import type { FroalaOptions } from 'froala-editor'

export const froalaDefaultOptions: Partial<FroalaOptions> = {
  initOnClick: false,
  toolbarInline: true,
  keepFormatOnDelete: true,
  toolbarVisibleWithoutSelection: false,
  quickInsertEnabled: true,
  pastePlain: false,
  charCounterCount: false,
  fontSizeSelection: true,
  fileMaxSize: 1024 * 1024 * 50,
  tabSpaces: 0, // otherwise tab key can not be prevented
  toolbarButtons: {
    moreText: {
      buttons: [
        'fontSize',
        'textColor',
        'backgroundColor',
        'bold',
        'italic',
        'underline',
        'strikeThrough',
        'subscript',
        'superscript',
        'fontFamily',
        'inlineClass',
        'inlineStyle',
        'clearFormatting',
      ],
      buttonsVisible: 3,
    },
    moreParagraph: {
      buttons: [
        'alignLeft',
        'alignCenter',
        'formatOLSimple',
        'alignRight',
        'alignJustify',
        'formatOL',
        'formatUL',
        'paragraphFormat',
        'paragraphStyle',
        'lineHeight',
        'outdent',
        'indent',
        'quote',
      ],
      buttonsVisible: 3,
    },
    moreRich: {
      buttons: [
        'insertLink',
        'insertTable',
        'insertImage',
        'insertVideo',
        'emoticons',
        'embedly',
        'fontAwesome',
        'specialCharacters',
        'insertFile',
        'insertHR',
        'html',
      ],
      buttonsVisible: 4,
    },
  },
  imageInsertButtons: ['imageBack', '|', 'imageUpload', 'imageByURL'],
  linkInsertButtons: ['linkBack'],
  imageEditButtons: [
    'imageReplace',
    'imageAlign',
    'imageRemove',
    '|',
    'imageLink',
    'linkOpen',
    'linkEdit',
    'linkRemove',
    '-',
    'imageDisplay',
    'imageStyle',
    'imageAlt',
    'imageSize',
  ],
  fontSize: [
    '6',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '18',
    '20',
    '24',
    '30',
    '36',
    '48',
    '60',
    '72',
    '96',
  ],
  fontFamily: {
    'sans-serif': 'Sans-serif',
    'Arial,Helvetica,sans-serif': 'Arial',
    'Georgia,serif': 'Georgia',
    'Impact,Charcoal,sans-serif': 'Impact',
    'Tahoma,Geneva,sans-serif': 'Tahoma',
    'Verdana,Geneva,sans-serif': 'Verdana',
    Helvetica: 'Helvetica',
    'Trebuchet MS': 'Trebuchet MS',
    "'Times New Roman',Times,serif": 'Times New Roman',
    Garamond: 'Garamond',
    'Courier New': 'Courier New',
    'Brush Script MT': 'Brush Script MT',
  },
  tableInsertHelper: false,
  tableInsertMaxSize: 12,
  inlineStyles: {
    'Big red': 'font-size: 20px; color: red;',
    'Small blue': 'font-size: 14px; color: blue;',
    'Bit bold': 'font-weight: 400;',
    'More bold': 'font-weight: 600;',
  },
  inlineClasses: {
    'fr-class-code': 'Code',
    'fr-class-highlighted': 'Highlighted',
    'fr-class-transparency': 'Transparent',
  },
  key: 'AVB8B-21D4B3B2E1F1G1uB-33B-21cyoF-10yB-7G-7gB-22zzE2wkA-7gC7B7D6B4E4F3D2I3H2C5==',
}
