# docker-compose -f docker-compose.prod.yml build
# docker-compose -f docker-compose.prod.yml build --no-cache
# docker-compose -f docker-compose.prod.yml up
services:
  backend:
    build:
      dockerfile: ./Dockerfile.prod.back
    ports:
      - '4000:4000'

  frontend:
    build:
      dockerfile: ./Dockerfile.prod.front
      args:
        BACKEND_URL: http://backend:4000
    ports:
      - '80:80'
    depends_on:
      - backend
