FROM node:20-alpine AS builder
RUN npm config set legacy-peer-deps true
WORKDIR /
COPY . .
RUN npm ci
RUN npm run build_back

FROM node:20-alpine
COPY --from=builder /back/build /back/build
WORKDIR /back/build
RUN npm ci
EXPOSE 4000
CMD ["node", "index.js"]
