# docker-compose -f docker-compose.prod.yaml build app_prod
# docker-compose -f docker-compose.prod.yaml up
services:
  app_prod:
    build: 
      dockerfile: Dockerfile.prod
    container_name: quotation.app.prod
    ports:
      - '4001:4001'
