FROM node:20-slim
RUN npm config set legacy-peer-deps true
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm i
WORKDIR /app/back
COPY package.json .
COPY package-lock.json .
RUN npm i
WORKDIR /app/front
COPY package.json .
COPY package-lock.json .
RUN npm i

WORKDIR /app
COPY . .
# port to listen on inside the container
EXPOSE 3000 
EXPOSE 4000
CMD ["npm", "run", "start"]