# docker-compose -f docker-compose.dev.yml build app_dev
# docker-compose -f docker-compose.dev.yml build app_dev --no-cache
# docker-compose -f docker-compose.dev.yml up

volumes:
  # issue with rollup - https://github.com/vitejs/vite/discussions/15532
  node_modules_root: # create empty volume (folder) on host machine and later mount /app/node_modules there
services:
  app_dev:
    container_name: quotation.app.dev
    build:
      dockerfile: Dockerfile.dev.all
    ports:
      - '3000:3000' # maps host machine port to container port
      - '4000:4000' # maps host machine port to container port
    volumes:
      - ./:/app # allows code changes on host to be reflected in the container --> live reload server
      # issue with rollup - https://github.com/vitejs/vite/discussions/15532
      - node_modules_root:/app/node_modules
