# docker-compose -f docker-compose.dev.yaml build app_dev
# docker-compose -f docker-compose.dev.yaml up

# issue with rollup - https://github.com/vitejs/vite/discussions/15532
volumes:
  node_modules_root: # create empty volume (folder) on our host machine and later mount /app/node_modules there
services:
  app_dev:
    container_name: quotation.app.dev
    build:
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000' # maps a container port to a host machine port
      - '4000:4000' # maps a container port to a host machine port
    volumes:
      - ./:/app # to monitor changes in project and live reload server
      - node_modules_root:/app/node_modules
