FROM node:22-alpine AS builder
RUN npm config set legacy-peer-deps true

# Install dependencies (cached unless package files change)
WORKDIR /
COPY package*.json ./
RUN npm ci

# Copy rest of the code (this invalidates cache only when code changes)
COPY . .

# Build
RUN npm run build_back

FROM node:22-alpine
COPY --from=builder /back/build /back/build
WORKDIR /back/build
RUN npm ci
EXPOSE 4000
ENV INSTALLATION=production
CMD ["node", "index.js"]
