FROM node:22-slim
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --legacy-peer-deps
WORKDIR /app/back
COPY package.json .
COPY package-lock.json .
RUN npm install --legacy-peer-deps
WORKDIR /app/front
COPY package.json .
COPY package-lock.json .
RUN npm install --legacy-peer-deps

WORKDIR /app
COPY . .
EXPOSE 3000
EXPOSE 4000
CMD ["npm", "run", "start"]