http {
  # Global Settings
  include mime.types; # Includes standard MIME types for serving files
  sendfile on; # Enables file transfer
  gzip on; # Enables Gzip compression for better performance
  client_max_body_size 50M; # Sets the maximum body size for requests (useful for file uploads)

  # Defines an upstream block for the backend service running on port 4000
  upstream backend {
    server backend:4000;
  }

  # HTTP Server Block
  server {
    listen 80;
    server_name _;
    index index.html index.htm;

    # Redirect to HTTPS in production based on environment variable
    set $is_production 0; # Default to local (no redirect)

    if ($http_host ~* sendmequotation\.today$) {
      set $is_production 1; # Enable redirect for production domain
    }

    if ($is_production) {
      return 301 https://$host$request_uri;
    }

    # Serve application files locally (no redirect)
    location / {
      root /front/build/; # Path to React build files
      try_files $uri /index.html; # Serve index.html for SPA routes
    }

    # Proxy API requests
    location /api {
      proxy_pass http://backend;
      proxy_ssl_verify off;
    }

    # Serve XML files like sitemap.xml
    location ~ \.xml$ {
      default_type application/xml;
    }
  }
}

events {
  worker_connections 1024;
}
