http {
  # Global Settings
  include mime.types; # Include standard MIME types
  sendfile on; # Enable efficient file transfers
  gzip on; # Enable Gzip compression for performance
  client_max_body_size 50M; # Allow larger request bodies (e.g., for file uploads)

  # Defines an upstream block for the backend service running on port 4000
  upstream backend {
    server backend:4000; # Backend service running on port 4000
  }

  # HTTP production Server Block
  server {
    listen 80;
    # Handle production domains only for the redirect
    server_name sendmequotation.today dev.sendmequotation.today;

    # Redirect to HTTPS only for production domains
    if ($scheme = http) {
      return 301 https://$host$request_uri;
    }

    # Serve React App for SPA
    location / {
      root /front/build/; # Path to React build files
      try_files $uri /index.html; # Serve index.html for SPA routes
    }

    # Proxy API Requests
    location /api {
      proxy_pass http://backend; # Forward API requests to backend
      proxy_ssl_verify off;
    }

    # Serve XML Files (e.g., sitemap.xml)
    location ~ \.xml$ {
      default_type application/xml; # Set content type for XML files
    }
  }

  # Local Development
  server {
    listen 80;
    server_name localhost 127.0.0.1;

    # Serve React App for Local Development without redirect
    location / {
      root /front/build/;
      try_files $uri /index.html; # Serve index.html for SPA routes
    }
    
    # Proxy API Requests for Local Development
    location /api {
      proxy_pass http://backend;
      proxy_ssl_verify off;
    }
  }
}

events {
  worker_connections 1024; # Set max number of connections
}