http {
  include mime.types;
  sendfile on;
  gzip on;
  client_max_body_size 50M;

  upstream backend {
    server backend:4000;
  }

  server {
    listen 80;
    server_name _;
    index index.html index.htm;

    # Redirect /blog to /blog/
    location = /blog {
      return 301 /blog/;
    }

    # Serve static blog files
    location /blog/ {
      root /front/build;
      try_files $uri $uri/ =404;

      types {
        text/html html htm;
        text/css css;
        application/javascript js;
      }
    }

    location /api {
      proxy_pass http://backend;
      proxy_ssl_verify off;
    }

    location /uploads {
      proxy_pass http://backend;
      proxy_ssl_verify off;
    }

    # React SPA (catch-all for all other routes)
    location / {
      root /front/build/; # <- directory where react bundle is stored
      try_files $uri /index.html; # <- serve index.html for any route
    }
  }
}

events {
  worker_connections 1024;
}
