export const apiUrl = {
  root: '/',
  api: '/api',
  test: '/api/test',
  register: '/api/register',
  logIn: '/api/login',
  logOut: '/api/logout',
  activate: '/api/activate',
  getAccessToken: '/api/get-access-token',
  requestPasswordReset: '/api/request-password-reset',
  resetPassword: '/api/reset-password',
  upload: '/api/upload',
  setBucketCors: '/api/set-bucket-cors',
  getBucketCors: '/api/get-bucket-cors',
  saveQuotation: '/api/save-quotation',
  saveItem: '/api/save-item',
  getQuotation: '/api/get-quotation',
  getQuotations: '/api/get-quotations',
  getItems: '/api/get-items',
  getItemCategories: '/api/get-item-categories',
  deleteQuotation: '/api/delete-quotation',
  deleteItem: '/api/delete-item',
} as const
