export { getPastePlace } from './getPastePlace'
export { getTextContentFromHtml } from './getTextContentFromHtml'
export { getNumberFromString } from './getNumberFromString'
export { getStringWithNewFormattedNumber } from './getStringWithNewFormattedNumber'
export { updateNumberAtHtmlIncrementally } from './updateNumberAtHtmlIncrementally'
export { updateNumberAtHtml } from './updateNumberAtHtml'
