export { getTextContentFromHtml } from './getTextContentFromHtml'
export { getNumberFromString } from './getNumberFromString'
export { getStringWithNewFormattedNumber } from './getStringWithNewFormattedNumber'
export { updateNumberAtHtmlIncrementally } from './froala/updateNumberAtHtmlIncrementally'
export { updateNumberAtHtml } from './froala/updateNumberAtHtml'
