export { saveItemsLocally } from './save_items_locally/saveItemsLocally'
export { getPastePlace } from './getPastePlace'
export { getTextContent } from './getTextContent'
export { getNumber } from './getNumber'
export { replaceNumber } from './replaceNumber'
