import { navItemId } from '@front/entities/nav/navItemId'
import { setNavStructure } from '@front/entities/nav/navStructureHolder'
import type { NavItem } from '@front/entities/nav/type'
import { route } from '@front/shared/lib/react-router-dom/route'

export const navStructure: NavItem[] = [
  {
    id: navItemId.burger,
    name: 'burger',
    iconId: 'burger',
    isHidden: false,
    nestedItemList: [
      {
        id: navItemId.back,
        iconId: 'back',
        isHidden: true,
        name: 'Back',
        funcId: 'openQuotationPageAndLoadPrev',
        isActive: true,
        tooltip: 'Back to quotation',
      },
      {
        id: navItemId.new,
        iconId: 'new',
        isHidden: false,
        name: 'New',
        link: route.new,
        funcId: 'openQuotationPageAndLoadNew',
        isActive: true,
        tooltip: 'New quotation',
      },
      {
        id: navItemId.save,
        iconId: 'save',
        isHidden: false,
        name: 'Save',
        maxName: 'Saving...',
        shortcut: ['control', 'shift', 's'],
        link: `./${route.save}`,
        tooltip: 'Save or update quotation (shortcut: ctrl+shift+s)',
        funcId: 'saveQuotation',
      },
      {
        id: navItemId.share,
        iconId: 'share',
        isHidden: false,
        name: 'Share',
        disabled: false,
        tooltip: 'Share / manage access',
        funcId: 'openShareQuotationModal',
      },
      {
        id: navItemId.download,
        iconId: 'download',
        isHidden: false,
        name: 'Download',
        disabled: false,
        tooltip: 'Download quotation',
        nestedItemList: [
          {
            id: navItemId.pdf,
            iconId: 'pdf',
            isHidden: false,
            disabled: false,
            name: 'Download as .pdf',
            tooltip: 'Download as .pdf',
            funcId: 'downloadPdf',
          },
          {
            id: navItemId.excel,
            iconId: 'excel',
            isHidden: false,
            disabled: false,
            name: 'Download as .xlsx',
            tooltip: 'Download as .xlsx',
            funcId: 'downloadExcel',
          },
        ],
      },
      {
        id: navItemId.insert,
        iconId: 'insert',
        isHidden: false,
        name: 'Insert',
        disabled: true,
        nestedItemList: [
          {
            id: navItemId.boqItem,
            name: 'Items',
            iconId: 'boqItem',
            isHidden: false,
            shortcut: ['control', 'shift', 'i'],
            funcId: 'insertBoqBlock',
          },
          {
            id: navItemId.row,
            name: 'Row',
            iconId: 'row',
            isHidden: false,
            shortcut: ['control', 'shift', 'r'],
            funcId: 'insertRow',
          },
          {
            id: navItemId.textItem,
            name: 'Text',
            iconId: 'textItem',
            isHidden: false,
            shortcut: ['control', 'shift', 't'],
            funcId: 'insertTextBlock',
          },
          {
            id: navItemId.priceItem,
            name: 'Price',
            iconId: 'priceItem',
            isHidden: false,
            shortcut: ['control', 'shift', 'p'],
            funcId: 'insertPriceBlock',
          },
          {
            id: navItemId.paymentItem,
            name: 'Payment',
            iconId: 'paymentItem',
            isHidden: false,
            funcId: 'insertPaymentBlock',
          },
        ],
        tooltip: 'Insert block or row',
      },
      {
        id: navItemId.bookmarkList,
        iconId: 'bookmarkList',
        isHidden: false,
        name: 'Bookmarks',
        link: route.bookmarkList,
        funcId: 'openBookmarksPage',
        tooltip: 'Your bookmarks',
      },
      {
        id: navItemId.quotationList,
        iconId: 'quotationList',
        isHidden: false,
        name: 'Quotations',
        link: route.quotationList,
        funcId: 'openQuotationsPage',
        tooltip: 'Your quotations',
      },
      {
        id: navItemId.blog,
        iconId: 'blog',
        isHidden: false,
        name: 'Blog',
        tooltip: 'Guides and resources',
        nestedItemList: [
          {
            id: navItemId.blogHowToCreate,
            name: 'How to Create Quotations',
            isHidden: false,
            externalLink: '/blog/how-to-create-quotation.html',
            tooltip: 'Step-by-step guide',
          },
          {
            id: navItemId.blogFreeTemplate,
            name: 'Free Templates',
            isHidden: false,
            externalLink: '/blog/free-quotation-template.html',
            tooltip: 'Ready-to-use templates',
          },
          {
            id: navItemId.blogTermsAndConditions,
            name: 'Terms & Conditions',
            isHidden: false,
            externalLink: '/blog/quotation-terms-and-conditions.html',
            tooltip: 'Essential legal terms',
          },
        ],
      },
      {
        id: navItemId.login,
        iconId: 'login',
        isHidden: false,
        name: 'Log in',
        link: `./${route.login}`,
        funcId: 'openLoginModal',
        tooltip: 'Log in',
      },
      {
        id: navItemId.profile,
        iconId: 'profile',
        name: 'Profile',
        isHidden: true,
        nestedItemList: [
          {
            id: navItemId.settings,
            iconId: 'settings',
            isHidden: false,
            name: 'Settings',
            link: `./${route.settings}`,
            funcId: 'openSettingsModal',
          },
          {
            id: navItemId.admin,
            iconId: 'admin',
            isHidden: false,
            name: 'Admin',
            tooltip: 'Admin links',
            nestedItemList: [
              {
                id: navItemId.quotationListAll,
                iconId: 'quotationList',
                isHidden: false,
                name: 'Quotations',
                link: `/${route.quotationListAll}`,
              },
              {
                id: navItemId.bookmarkListAll,
                iconId: 'bookmarkList',
                isHidden: false,
                name: 'Bookmarks',
                link: `/${route.bookmarkListAll}`,
              },
              {
                id: navItemId.fileListAll,
                iconId: 'fileListAll',
                isHidden: false,
                name: 'Files',
                link: `/${route.fileListAll}`,
              },
              {
                id: navItemId.userList,
                iconId: 'userList',
                isHidden: false,
                name: 'Users',
                link: `/${route.userList}`,
              },
              {
                id: navItemId.visitors,
                iconId: 'visitors',
                isHidden: false,
                name: 'Visitors',
                link: `/${route.visitorList}`,
              },
            ],
          },
          {
            id: navItemId.logout,
            iconId: 'logout',
            isHidden: false,
            name: 'Log out',
            link: `./${route.logout}`,
          },
        ],
        tooltip: 'Profile, settings',
      },
    ],
  },
]

setNavStructure(navStructure)
