export const apiUrl = {
  root: '/',
  api: '/api',
  hi: '/api/hi',
  test: '/api/test',
  register: '/api/register',
  login: '/api/login',
  logout: '/api/logout',
  activate: '/api/activate',
  refresh: '/api/refresh',
  users: '/api/users',
  user: '/api/user',
  reset: '/api/reset',
  upload: '/api/upload',
  setBucketCors: '/api/set-bucket-cors',
  getBucketCors: '/api/get-bucket-cors',
} as const
