export const queryKey = {
  // auth
  logIn: 'logIn',
  logOut: 'logOut',
  activate: 'activate',
  register: 'register',
  requestPasswordReset: 'requestPasswordReset',
  resetPassword: 'resetPassword',
  getAccessToken: 'getAccessToken',
  // users
  deleteUser: 'deleteUser',
  getUserList: 'getUserList',
  // quotation
  getQuotation: 'getQuotation',
  saveQuotation: 'saveQuotation',
  deleteQuotation: 'deleteQuotation',
  getQuotationList: 'getQuotationList',
  getQuotationCategoryList: 'getQuotationCategoryList',
  // file
  deleteFile: 'deleteFile',
  getFileListStats: 'getFileListStats',
  // bookmark
  getBookmark: 'getBookmark',
  saveBookmark: 'saveBookmark',
  deleteBookmark: 'deleteBookmark',
  getBookmarkList: 'getBookmarkList',
  getBookmarkCategoryList: 'getBookmarkCategoryList',
  // visitors
  countUniqueDailyVisitors: 'countUniqueDailyVisitors',
  getUniqueDailyVisitors: 'getUniqueDailyVisitors',
  // dev
  healthCheck: 'healthCheck',
} as const
