export { getTextContentFromHtml } from './getTextContentFromHtml'
export { getNumberFromString } from './getNumberFromString'
export { getStringWithNewFormattedNumber } from './getStringWithNewFormattedNumber'
export { getFileSizeInMbAsText } from './getFileSize'
export { getPaperElementHtml } from './getPaperElementHtml'
