export { getTextContentFromHtml } from './getTextContentFromHtml'
export { getNumberFromString } from './getNumberFromString'
export { getStringWithNewFormattedNumber } from './getStringWithNewFormattedNumber'
export { getFileSizeInMbAsText } from './getFileSize'
export { getClosestPaperElementHtml } from './htmlGetter/getClosestPaperElementHtml'
