# Generated from config/configVariables.ts

project_id = "quotationapp-8014c"
project_number = "665701178658"
region = "us-central1"
github_repository = "antonarbus/q"
bucket_for_terraform_state_name = "quotationapp-terraform-state"
artifact_registry_name = "docker-images"
docker_image_name_frontend = "web-app-frontend"
docker_image_name_backend = "web-app-backend"
github_actions_sa_name = "github-actions-sa"
cloud_run_sa_name = "cloud-run-sa"
min_instances_frontend = "0"
max_instances_frontend = "5"
cpu_limit_frontend = "1"
memory_limit_frontend = "512Mi"
container_port_frontend = "80"
min_instances_backend = "0"
max_instances_backend = "5"
cpu_limit_backend = "1"
memory_limit_backend = "512Mi"
container_port_backend = "4000"
cloud_run_service_name_frontend = "web-app-frontend-prod"
cloud_run_service_name_backend = "web-app-backend-prod"
custom_domain_frontend = "sendmequotation.today"
environment = "prod"
