export type FunctionId =
  | 'downloadExcel'
  | 'downloadPdf'
  | 'insertBoqBlock'
  | 'insertPaymentBlock'
  | 'insertPriceBlock'
  | 'insertRow'
  | 'insertTextBlock'
  | 'openBookmarksPage'
  | 'openLoginModal'
  | 'openQuotationPageAndLoadNew'
  | 'openQuotationPageAndLoadPrev'
  | 'openQuotationsPage'
  | 'openSettingsModal'
  | 'openShareQuotationModal'
  | 'saveQuotation'
