export const navItemId = {
  burger: 'burger',
  pending: 'pending',
  new: 'new',
  save: 'save',
  share: 'share',
  download: 'download',
  pdf: 'pdf',
  link: 'link',
  excel: 'excel',
  insert: 'insert',
  quotationList: 'quotation-list',
  quotationListAll: 'quotation-list-all',
  bookmarkList: 'bookmark-list',
  bookmarkListAll: 'bookmark-list-all',
  fileListAll: 'file-list-all',
  login: 'login',
  profile: 'profile',
  settings: 'settings',
  logout: 'logout',
  textItem: 'textItem',
  boqItem: 'boqItem',
  priceItem: 'priceItem',
  paymentItem: 'paymentItem',
  row: 'row',
  back: 'back',
  admin: 'admin',
  userList: 'user-list',
  visitors: 'visitors',
  blog: 'blog',
  blogAbout: 'blog-about',
  blogFaq: 'blog-faq',
  welcomeGuide: 'welcome-guide',
} as const

export type NavItemId = (typeof navItemId)[keyof typeof navItemId]
