export const queryKey = {
  // auth
  logIn: 'log-in',
  logOut: 'log-out',
  activate: 'activate',
  register: 'register',
  requestPasswordReset: 'request-password-reset',
  resetPassword: 'reset-password',
  getAccessToken: 'get-access-token',
  // users
  deleteUser: 'delete-user',
  getUserList: 'get-user-list',
  // quotation
  getQuotation: 'get-quotation',
  saveQuotation: 'save-quotation',
  deleteQuotation: 'delete-quotation',
  getQuotationList: 'get-quotation-list',
  getQuotationCategoryList: 'get-quotation-category-list',
  // file
  deleteFile: 'delete-file',
  getFileListStats: 'get-file-list-stats',
  // bookmark
  getBookmark: 'get-bookmark',
  saveBookmark: 'save-bookmark',
  deleteBookmark: 'delete-bookmark',
  getBookmarkList: 'get-bookmark-list',
  getBookmarkCategoryList: 'get-bookmark-category-list',
  // visitors
  countUniqueDailyVisitors: 'count-unique-daily-visitors',
  getUniqueDailyVisitors: 'get-unique-daily-visitors',
  // stripe
  stripeAccountStatus: 'stripe-account-status',
  stripeDisconnect: 'stripe-disconnect',
  stripeCreatePaymentLink: 'stripe-create-payment-link',
  stripeSubscriptionStatus: 'stripe-subscription-status',
  stripeSubscriptionCheckout: 'stripe-subscription-checkout',
  // ai
  suggestion: 'suggestion',
  // dev
  healthCheck: 'health-check',
} as const
