name: CI and CD Pipeline to Cloud Run

env:
  PROJECT_ID: 'quotationapp-8014c'
  REGION: 'us-central1'
  ARTIFACTS_REGISTRY_NAME: 'cloud-run'
  DOCKER_IMAGE_NAME: 'docker-image'
  INSTALLATION: 'local'
  CI: 'true'
  BACKEND_URL_MAIN: 'https://api.sendmequotation.today'
  BACKEND_URL_DEV: 'https://api-dev.sendmequotation.today'

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev
    types:
      - closed

jobs:
  TypeScript-and-other-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.38'

      - name: Install all dependencies
        run: bun run install_all

      - name: Run Biome (formatting + linting)
        run: bun run biome:silent

      - name: Run unit tests
        run: bun run test

      - name: Find unused code
        run: bun run find_unused_files

      - name: Find circular dependencies
        run: bun run circular_deps

      - name: Run TypeScript checks
        run: bun run tsc

  e2e-tests:
    runs-on: ubuntu-latest
    
    # Must match local installation, when upgrading Playwright locally, update this version to match.
    # Available containers: https://playwright.dev/docs/docker#image-tags
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip
        run: |
          apt-get update
          apt-get install -y unzip

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.38'

      - name: Install all dependencies
        run: bun run install_all

      - name: Run Playwright tests
        run: bun run playwright

  deploy-backend:
    needs: [TypeScript-and-other-checks, e2e-tests]
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    outputs:
      backend_url: ${{steps.deploy-cloud-run-back.outputs.url}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_SA_KEY}}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{env.REGION}}-docker.pkg.dev'

      - name: Set environment variables
        id: set-env
        run: |
          echo "IMAGE_VERSION=${{github.ref_name}}" >> $GITHUB_ENV

      - name: Build and push Docker image Backend
        id: build-push-back
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod.back
          push: true
          tags: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-back:${{env.IMAGE_VERSION}}

      - name: Deploy to Cloud Run Backend
        id: deploy-cloud-run-back
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cloud-run-backend-${{env.IMAGE_VERSION}}
          image: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-back:${{env.IMAGE_VERSION}}
          region: ${{env.REGION}}
          project_id: ${{env.PROJECT_ID}}
          flags: --port 4000 --allow-unauthenticated

  deploy-frontend:
    needs: [TypeScript-and-other-checks, e2e-tests]
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    outputs:
      frontend_url: ${{steps.deploy-cloud-run-front.outputs.url}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_SA_KEY}}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{env.REGION}}-docker.pkg.dev'

      - name: Set environment variables
        id: set-env
        run: |
          echo "IMAGE_VERSION=${{github.ref_name}}" >> $GITHUB_ENV
          if [ "${{github.ref_name}}" == "main" ]; then
            echo "BACKEND_URL=${{env.BACKEND_URL_MAIN}}" >> $GITHUB_ENV
          elif [ "${{github.ref_name}}" == "dev" ]; then
            echo "BACKEND_URL=${{env.BACKEND_URL_DEV}}" >> $GITHUB_ENV
          else
            echo "Error: Unknown branch ${{github.ref_name}}"
            exit 1
          fi

      - name: Build and push Docker image Frontend
        id: build-push-front
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod.front
          push: true
          tags: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-front:${{env.IMAGE_VERSION}}
          build-args: |
            BACKEND_URL=${{env.BACKEND_URL}}

      - name: Deploy to Cloud Run Frontend
        id: deploy-cloud-run-front
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cloud-run-frontend-${{env.IMAGE_VERSION}}
          image: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-front:${{env.IMAGE_VERSION}}
          region: ${{env.REGION}}
          project_id: ${{env.PROJECT_ID}}
          flags: --port 80 --allow-unauthenticated

  test-deployment:
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Test backend endpoint
        run: |
          curl "${{needs.deploy-backend.outputs.backend_url}}" -I -s | grep "HTTP/2 200"

      - name: Test frontend endpoint
        run: |
          curl "${{needs.deploy-frontend.outputs.frontend_url}}" -I -s | grep "HTTP/2 200"
