name: CI and CD Pipeline to Cloud Run

env:
  PROJECT_ID: 'quotationapp-8014c'
  REGION: 'us-central1'
  ARTIFACTS_REGISTRY_NAME: 'cloud-run'
  DOCKER_IMAGE_NAME: 'docker-image'
  INSTALLATION: 'local'
  CI: 'true'

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev
    types:
      - closed

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_SA_KEY}}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{env.REGION}}-docker.pkg.dev'

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Print Node version
        run: echo "Node.js version:$(node --version)"

      - name: Disable npm installation checks
        run: npm config set legacy-peer-deps true

      - name: Install dev dependencies
        run: npm run install_dev_deps

      - name: Install front dependencies
        run: npm run install_front

      - name: Install back dependencies
        run: npm run install_back

      - name: Run Biome (formatting + linting)
        run: npm run biome:silent
        
      - name: Run unit tests
        run: npm run test

      - name: Run TypeScript checks
        run: npm run tsc


      - name: Run Playwright tests
        run: npm run playwright

      - name: Set environment variables
        id: set-env
        run: |
          echo "IMAGE_VERSION=${{github.ref_name}}" >> $GITHUB_ENV

      - name: Build and push Docker image Backend
        id: build-push-back
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod.back
          push: true
          tags: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-back:${{env.IMAGE_VERSION}}

      - name: Deploy to Cloud Run Backend
        id: deploy-cloud-run-back
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cloud-run-backend-${{env.IMAGE_VERSION}}
          image: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-back:${{env.IMAGE_VERSION}}
          region: ${{env.REGION}}
          project_id: ${{env.PROJECT_ID}}
          flags: --port 4000 --allow-unauthenticated

      - name: Change backend stream NGINX config
        run: |
          DOMAIN=$(echo ${{steps.deploy-cloud-run-back.outputs.url}} | cut -d'/' -f3)
          echo "DOMAIN: ${DOMAIN}"
          sed -i 's|backend:4000|'${DOMAIN}'|g' ./nginx.conf
          sed -i 's|http://backend|https://'${DOMAIN}'|g' ./nginx.conf
          cat ./nginx.conf

      - name: Build and push Docker image Frontend
        id: build-push-front
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod.front
          push: true
          tags: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-front:${{env.IMAGE_VERSION}}

      - name: Deploy to Cloud Run Frontend
        id: deploy-cloud-run-front
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cloud-run-frontend-${{env.IMAGE_VERSION}}
          image: ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.ARTIFACTS_REGISTRY_NAME}}/${{env.DOCKER_IMAGE_NAME}}-front:${{env.IMAGE_VERSION}}
          region: ${{env.REGION}}
          project_id: ${{env.PROJECT_ID}}
          flags: --port 80 --allow-unauthenticated

      - name: Test Cloud Run
        run: |
          curl "${{steps.deploy-cloud-run-back.outputs.url}}" -I -s | grep "HTTP/2 200"
          curl "${{steps.deploy-cloud-run-front.outputs.url}}" -I -s | grep "HTTP/2 200"
