export const cls = {
  droppable: 'droppable',
  seo: 'seo',
  waitForInitFilesToLoad: 'wait-for-init-files-to-load',
  blocks: 'blocks',
  block: 'block',
  boqBlock: 'boq-block',
  priceBlock: 'price-block',
  textBlock: 'text-block',
  paper: 'paper',
  boqRows: 'boq-rows',
  boqRow: 'boq-row',
  pin: 'pin',
  searchAutocomplete: 'search-autocomplete',
  search: 'search',
  actionsContainer: 'actions-container',
  actionIconContainer: 'action-icon-container',
  actionIcon: 'action-icon',
  formModal: 'form-modal',
  dropFilesText: 'drop-files-text',
  dropHereText: 'drop-here-text',
  cleanFromPaper:
    '.fr-placeholder,.right-resize-handle,.left-resize-handle,.actions-container,#DndDescribedBy-1,#DndLiveRegion-0,.drop-files-text,.drop-here-text',
} as const
