export const route = {
  root: '/',
  login: 'login',
  logout: 'logout',
  register: 'register',
  requestPasswordReset: 'request-password-reset',
  resetPassword: 'reset-password',
  activate: 'activate',
  new: 'new',
  quotationList: 'quotation-list',
  quotationListAll: 'quotation-list-all',
  save: 'save',
  share: 'share',
  bookmarkList: 'bookmark-list',
  bookmarkListAll: 'bookmark-list-all',
  bookmark: 'bookmark',
  fileListAll: 'file-list-all',
  info: 'info',
  settings: 'settings',
  userList: 'user-list',
  visitorList: 'visitor-list',
} as const
