export const navItemId = {
  top: 'top',
  pending: 'pending',
  new: 'new',
  save: 'save',
  pdf: 'pdf',
  share: 'share',
  insert: 'insert',
  quotations: 'quotations',
  bookmarks: 'bookmarks',
  login: 'login',
  account: 'account',
  settings: 'settings',
  profile: 'profile',
  logout: 'logout',
  block: 'block',
  textItem: 'textItem',
  boqItem: 'boqItem',
  priceItem: 'priceItem',
  boqRow: 'boqRow',
} as const
