export const queryKey = {
  getQuotation: 'getQuotation',
  getQuotations: 'getQuotations',
  getItems: 'getItems',
  getItemCategories: 'getItemCategories',
  deleteQuotation: 'deleteQuotation',
  deleteItem: 'deleteItem',
  logIn: 'logIn',
  logOut: 'logOut',
  activate: 'activate',
  register: 'register',
  requestPasswordReset: 'requestPasswordReset',
  resetPassword: 'resetPassword',
  saveQuotation: 'saveQuotation',
  saveItem: 'saveItem',
  getAccessToken: 'getAccessToken',
} as const
