export const route = {
  root: '/',
  login: 'login',
  logout: 'logout',
  register: 'register',
  requestPasswordReset: 'request-password-reset',
  resetPassword: 'reset-password',
  activate: 'activate',
  quotations: 'quotations',
  items: 'items',
  settings: 'settings',
  new: 'new',
  saveQuotation: 'save-quotation',
  editQuotation: 'edit-quotation',
  quotationInfo: 'quotation-info',
  saveItem: 'save-item',
  editItem: 'edit-item',
  itemInfo: 'item-info',
} as const
