export const route = {
  root: '/',
  login: 'login',
  logout: 'logout',
  register: 'register',
  requestPasswordReset: 'request-password-reset',
  resetPassword: 'reset-password',
  activate: 'activate',
  quotations: 'quotations',
  bookmarks: 'bookmarks',
  settings: 'settings',
  new: 'new',
  saveQuotation: 'save-quotation',
  editQuotation: 'edit-quotation',
  quotationInfo: 'quotation-info',
  bookmark: 'bookmark',
  editBookmark: 'edit-bookmark',
  itemInfo: 'item-info',
} as const
