export const route = {
  root: '/',
  login: 'login',
  logout: 'logout',
  register: 'register',
  requestPasswordReset: 'request-password-reset',
  resetPassword: 'reset-password',
  activate: 'activate',
  quotations: 'quotations',
  items: 'items',
  settings: 'settings',
  save: 'save',
  new: 'new',
  saveItem: 'save-item',
} as const
